# Generated by Django 4.1.7 on 2023-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=10),
        ),
    ]
