# Generated by Django 4.1.7 on 2023-03-16 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_date_alter_todo_id_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
